### ISSUE TITLE
Sticky notes transformer

### ISSUE THREAD

**Issue by ruchirlives** [emilefokkema/infinite-canvas#11]
Hi. I'd like to add sticky notes that stick to the correct transformed location when zoomed and panned. Any ideas?

**Comment by emilefokkema** [comment]
Hi, for now the only way I can think of is to subscribe to an `InfiniteCanvas`'s `draw` event, like
```
infCanvas.addEventListener('draw', e => { ... })
```
where `e` will have a property `transformation`, which will be an object with properties `a`, `b`, `c` ,`d`, `e` and `f`. You can use these values to calculate the correct position of your sticky note and then use *another canvas* (not the `InfiniteCanvas`'s one) to draw  it.

I know this is kind of cumbersome, and the issue is a very good one. I have thought a lot about ways to integrate something like this into `InfiniteCanvas`'s api in a consistent and understandable way, but I haven't been able to think of anything yet. Suggestions are of course welcome.

**Comment by ruchirlives** [comment]
Here’s my app https://github.com/ruchirlives/infinitezoomtree
Would welcome your comments.

**Comment by emilefokkema** [comment]
Sorry for my late reply. I looked at your app and I like it. It demonstrates the need for a 'click' event on the InfiniteCanvas, which would contain the coordinates of the click in the transformed space. That way you wouldn't have to dive into the `ctx.canvasTransform.viewBox.canvasRectangle.coordinateSystems...`. I'm thinking of adding that feature soon.

**Comment by emilefokkema** [comment]
Hi @ruchirlives , there is a new version of `InfiniteCanvas`, [0.6.0-alpha](https://github.com/emilefokkema/infinite-canvas/releases/tag/v0.6.0-alpha), in which an `InfiniteCanvas` has a [`transformation`](https://infinite-canvas.org/#/api/interfaces/InfiniteCanvas?id=transformation) property that contains the `a`, `b`, `c`, `d`, `e` and `f` directly, without you having to dig into `ctx.canvasTransform.viewBox.canvasRectangle.coordinateSystems` etc. I created a [PR](https://github.com/ruchirlives/infinitezoomtree/pull/1) in your project that demonstrates how you might make use of it.
