### ISSUE TITLE
Uncaught error calculating inverse: zero determinant

### ISSUE THREAD

**Issue by agnieszkajust** [emilefokkema/infinite-canvas#33]
Hello,
I get error:
"Uncaught error calculating inverse: zero determinant" 
after running code with this line:
const canvas_src = new InfiniteCanvas(document.createElement("canvas"))

Is it possible to set document.createElement("canvas") as an argument InfiniteCanvas?

**Comment by emilefokkema** [comment]
This error occurs because the canvas element that you're using for your `InfiniteCanvas` has not yet been attached to the page, which is why it has no width or height, and `InfiniteCanvas` has trouble initializing. See [this example](https://stackblitz.com/edit/gcifpt?file=index.js) on Stackblitz. I could throw a more explanatory error, I suppose.
